package clientside;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;

import javax.sound.sampled.FloatControl;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javazoom.jl.decoder.Bitstream;
import javazoom.jl.decoder.Header;
import javazoom.jl.player.Player;

/**
 *
 * @author azazel
 */
public class MainScreen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MainScreen.class.getName());

    private int serverPort = 1124;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        emptyDefaultListSong();
        loadSongs();
        btnStop.addActionListener(e -> stopStreaming());
        btnNext.addActionListener(e -> nextSong());
        btnPrevious.addActionListener(e -> previousSong());

        slidAudioVolume.setMinimum(0);
        slidAudioVolume.setMaximum(100);
        slidAudioVolume.setValue(80);

        // add a single ChangeListener that applies the slider to the discovered gain
        // control
        slidAudioVolume.addChangeListener(e -> setVolumeFromSlider(slidAudioVolume.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pbarAudioProgress = new javax.swing.JProgressBar();
        lblStartTimer = new javax.swing.JLabel();
        lblEndTimer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSongs = new javax.swing.JList<>();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        lblSongName = new javax.swing.JLabel();
        slidAudioVolume = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblStartTimer.setText("00:00");

        lblEndTimer.setText("00:00");

        listSongs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listSongs);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setText("Stop");

        btnNext.setText("Next");

        btnPrevious.setText("Previous");

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        lblSongName.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblStartTimer)
                                .addGap(378, 378, 378)
                                .addComponent(slidAudioVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEndTimer))
                            .addComponent(pbarAudioProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpload))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(lblSongName)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSongName)
                .addGap(9, 9, 9)
                .addComponent(pbarAudioProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStartTimer)
                            .addComponent(lblEndTimer))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(slidAudioVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart)
                            .addComponent(btnStop)
                            .addComponent(btnNext)
                            .addComponent(btnPrevious))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpload)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Socket streamingSocket;
    private Thread playerThread;
    private Player mp3Player;

    // field: current gain control if we find it via reflection
    private volatile FloatControl currentGainControl = null;

    // Playback timing
    private Timer progressTimer;
    private long playbackStartMs = 0L;
    private long elapsedBeforePaused = 0L;
    private long estimateDurationsMs = -1L;

    /**
     * Format time is mm:ss
     */
    private static String formatTime(long ms) {
        if (ms < 0)
            return "--:--";
        long totalSeconds = ms / 1000;
        long minutes = totalSeconds / 60;
        long seconds = totalSeconds % 60;
        return String.format("%02d:%02d", minutes, seconds);
    }

    /**
     * Start/Stop timer in swing timer
     */
    private void startProgressTimer() {
        if (progressTimer != null && progressTimer.isRunning()) {
            progressTimer.stop();
        }

        progressTimer = new Timer(500, e -> {
            long elapsed = 0;
            if (playbackStartMs > 0) {
                elapsed = System.currentTimeMillis() - playbackStartMs + elapsedBeforePaused;
            }
            lblStartTimer.setText(formatTime(elapsed));

            if (estimateDurationsMs > 0) {
                int percent = (int) ((elapsed * 100L) / Math.max(1L, estimateDurationsMs));
                percent = Math.min(Math.max(percent, 0), 100);
                pbarAudioProgress.setIndeterminate(false);
                pbarAudioProgress.setValue(percent);
            } else {
                pbarAudioProgress.setIndeterminate(true);
            }
        });

        playbackStartMs = System.currentTimeMillis();
        progressTimer.setInitialDelay(0);
        progressTimer.start();
    }

    private void stopProgressTimer() {
        if (progressTimer != null) {
            progressTimer.stop();
            progressTimer = null;
        }
        lblStartTimer.setText("00:00");
        pbarAudioProgress.setValue(0);
        pbarAudioProgress.setIndeterminate(false);
        playbackStartMs = 0L;
        elapsedBeforePaused = 0L;
        estimateDurationsMs = -1L;
    }

    /**
     * Previous song for btnPrevious
     */
    private void previousSong() {
        ListModel<String> model = listSongs.getModel();

        int size = model.getSize();
        if (size == 0) {
            JOptionPane.showMessageDialog(this, "There are no songs available");
            return;
        }

        int current = listSongs.getSelectedIndex();
        int previousIndex;

        if (current <= 0) {
            previousIndex = size - 1;
        } else {
            previousIndex = current - 1;
        }

        // set selected song and make it visible
        listSongs.setSelectedIndex(previousIndex);
        listSongs.ensureIndexIsVisible(previousIndex);

        String previousSong = model.getElementAt(previousIndex);
        streamingAndPlay(previousSong);
    }

    /**
     * Next song function for btnNext
     */
    private void nextSong() {
        ListModel<String> model = listSongs.getModel();

        int size = model.getSize();
        if (size == 0) {
            JOptionPane.showMessageDialog(this, "No songs available");
            return;
        }

        int current = listSongs.getSelectedIndex();
        int nextIndex;

        // if at the end of list song and click next button will
        if (current < 0 || current >= size - 1) {
            nextIndex = 0;
        } else {
            nextIndex = current + 1;
        }

        // set selected and visible
        listSongs.setSelectedIndex(nextIndex);
        listSongs.ensureIndexIsVisible(nextIndex);

        String nextSong = model.getElementAt(nextIndex);

        streamingAndPlay(nextSong);
    }

    /**
     * This function use for streaming after play button click
     */
    private void streamingAndPlay(String fileName) {
        stopStreaming();

        playerThread = new Thread(() -> {
            try {
                streamingSocket = new Socket(InetAddress.getByName("localhost"), serverPort);

                DataOutputStream dos = new DataOutputStream(streamingSocket.getOutputStream());
                DataInputStream dis = new DataInputStream(streamingSocket.getInputStream());

                dos.writeUTF("STREAMING");
                dos.writeUTF(fileName);
                dos.flush();

                long fileSize = dis.readLong();

                // If file size smaller than 0 then it's mean no file found
                if (fileSize < 0) {
                    lblSongName.setText("Not found " + fileName);
                    SwingUtilities
                            .invokeLater(() -> JOptionPane.showInputDialog(this, "File not found on this server"));
                    closeQuietly(dis, dos, streamingSocket);
                    return;
                }

                // wrap socket stream and allow reset after reading header
                BufferedInputStream bis = new BufferedInputStream(streamingSocket.getInputStream());
                bis.mark(64 * 1024); // reserve mark (64KB should be enough for header/framing)

                // try to read first MP3 header(s) to estimate bitrate.
                // We normalize to bits-per-second (bps) because different jlayer versions
                // may return bitrate in kbps or bps.
                long bitrateBps = -1L;
                try {
                    Bitstream headerBs = new Bitstream(bis);
                    // Try a few frames because the first may be an ID3v2 tag or invalid
                    for (int i = 0; i < 6 && bitrateBps <= 0; i++) {
                        Header header = headerBs.readFrame();
                        if (header == null)
                            break;
                        int raw = -1;
                        try {
                            raw = header.bitrate(); // may be kbps (e.g. 128) or bps (e.g. 128000)
                        } catch (Throwable ignored) {
                        }
                        headerBs.closeFrame();
                        if (raw > 0) {
                            if (raw > 1000) {
                                // very likely already in bits-per-second
                                bitrateBps = raw;
                            } else {
                                // likely kbps -> convert to bps
                                bitrateBps = (long) raw * 1000L;
                            }
                            break;
                        }
                    }
                } catch (Throwable t) {
                    // unable to read header(s) — we'll fall back below
                } finally {
                    try {
                        bis.reset();
                    } catch (IOException ignored) {
                    }
                }

                // Fallback to a safe default if detection failed (128 kbps)
                if (bitrateBps <= 0) {
                    bitrateBps = 128_000L;
                    logger.fine("Could not detect MP3 bitrate; using fallback 128 kbps (128000 bps).");
                } else {
                    logger.fine("Detected bitrate (bps): " + bitrateBps);
                }

                // estimate duration in milliseconds:
                // fileSize (bytes) -> bits = fileSize * 8
                // seconds = bits / bitrateBps
                // ms = seconds * 1000 => ms = bits * 1000 / bitrateBps
                estimateDurationsMs = (fileSize * 8L * 1000L) / Math.max(1L, bitrateBps);

                // update UI on EDT
                SwingUtilities.invokeLater(() -> {
                    lblEndTimer.setText(formatTime(estimateDurationsMs));
                    pbarAudioProgress.setIndeterminate(false);
                    pbarAudioProgress.setMaximum(100); // percent mode 0..100
                    pbarAudioProgress.setValue(0);
                });

                // create player and start playback
                BufferedInputStream playerBis = bis; // we already reset bis
                mp3Player = new Player(playerBis);

                new Thread(() -> {
                    java.lang.reflect.Field audioField;
                    FloatControl found = null;
                    for (int attempt = 0; attempt < 20 && found == null; attempt++) { // try for ~2s
                        try {
                            audioField = Player.class.getDeclaredField("audio");
                            audioField.setAccessible(true);
                            Object audioDev = audioField.get(mp3Player);
                            if (audioDev != null) {
                                // try to find a SourceDataLine field
                                for (java.lang.reflect.Field f : audioDev.getClass().getDeclaredFields()) {
                                    if (javax.sound.sampled.SourceDataLine.class.isAssignableFrom(f.getType())) {
                                        f.setAccessible(true);
                                        Object maybeLine = f.get(audioDev);
                                        if (maybeLine instanceof javax.sound.sampled.SourceDataLine) {
                                            javax.sound.sampled.SourceDataLine line = (javax.sound.sampled.SourceDataLine) maybeLine;
                                            if (line.isControlSupported(
                                                    javax.sound.sampled.FloatControl.Type.MASTER_GAIN)) {
                                                found = (FloatControl) line
                                                        .getControl(javax.sound.sampled.FloatControl.Type.MASTER_GAIN);
                                                break;
                                            }
                                        }
                                    }
                                }
                                // fallback named fields
                                if (found == null) {
                                    try {
                                        java.lang.reflect.Field lf = audioDev.getClass().getDeclaredField("line");
                                        lf.setAccessible(true);
                                        Object maybeLine = lf.get(audioDev);
                                        if (maybeLine instanceof javax.sound.sampled.SourceDataLine) {
                                            javax.sound.sampled.SourceDataLine line = (javax.sound.sampled.SourceDataLine) maybeLine;
                                            if (line.isControlSupported(
                                                    javax.sound.sampled.FloatControl.Type.MASTER_GAIN)) {
                                                found = (FloatControl) line
                                                        .getControl(javax.sound.sampled.FloatControl.Type.MASTER_GAIN);
                                            }
                                        }
                                    } catch (NoSuchFieldException ignored) {
                                    }
                                    try {
                                        java.lang.reflect.Field lf = audioDev.getClass().getDeclaredField("source");
                                        lf.setAccessible(true);
                                        Object maybeLine = lf.get(audioDev);
                                        if (maybeLine instanceof javax.sound.sampled.SourceDataLine) {
                                            javax.sound.sampled.SourceDataLine line = (javax.sound.sampled.SourceDataLine) maybeLine;
                                            if (line.isControlSupported(
                                                    javax.sound.sampled.FloatControl.Type.MASTER_GAIN)) {
                                                found = (FloatControl) line
                                                        .getControl(javax.sound.sampled.FloatControl.Type.MASTER_GAIN);
                                            }
                                        }
                                    } catch (NoSuchFieldException ignored) {
                                    }
                                }
                            }
                        } catch (Throwable ignored) {
                            // reflection may fail on some builds; retry a few times
                        }
                        if (found != null)
                            break;
                        try {
                            Thread.sleep(100);
                        } catch (InterruptedException ie) {
                            break;
                        }
                        if (playerThread == null || !playerThread.isAlive())
                            break;
                    }

                    if (found != null) {
                        currentGainControl = found;
                        // apply current slider value on EDT
                        SwingUtilities.invokeLater(() -> setVolumeFromSlider(slidAudioVolume.getValue()));
                    }
                }, "GainFinder-Thread").start();

                // start timers right before play
                SwingUtilities.invokeLater(() -> {
                    lblSongName.setText("Playing: " + fileName);
                    startProgressTimer();
                });

                mp3Player.play(); // will block until playback finished (in playerThread)

                // after play() returns and before stopProgressTimer()
                if (estimateDurationsMs > 0) {
                    SwingUtilities.invokeLater(() -> lblStartTimer.setText(formatTime(estimateDurationsMs)));
                }
                stopProgressTimer();
            } catch (Exception e) {
                // TODO: handle exception
                e.printStackTrace();
                SwingUtilities
                        .invokeLater(() -> JOptionPane.showMessageDialog(this, "Playback error: " + e.getMessage()));
                closeQuietly(null, null, streamingSocket);
            }
        }, "MP3-Player-Thread");
        playerThread.start();
    }

    private void closeQuietly(DataInputStream dis, DataOutputStream dos, Socket streamingSocket) {
        try {
            if (dis != null)
                dis.close();
        } catch (Exception e) {
            // ignore
        }
        try {
            if (dos != null)
                dos.close(); // <-- fixed: close dos, not dis again
        } catch (Exception e) {
            // ignore
        }
        try {
            if (streamingSocket != null)
                streamingSocket.close();
        } catch (Exception e) {
            // ignore
        }
    }

    private void stopStreaming() {
        try {
            if (mp3Player != null) {
                mp3Player.close(); // will cause play() to stop
                mp3Player = null;
            }
        } catch (Exception e) {
            // TODO: handle exception
        }

        try {
            if (streamingSocket != null && !streamingSocket.isClosed()) {
                streamingSocket.close();
                streamingSocket = null;
            }
        } catch (Exception e) {
            // TODO: handle exception
        }

        if (playerThread != null && playerThread.isAlive()) {
            playerThread.interrupt();
            playerThread = null;
        }
    }

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        String selected = listSongs.getSelectedValue();

        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Please select a song to play");
            return;
        }

        streamingAndPlay(selected);
    }// GEN-LAST:event_btnStartActionPerformed

    private DefaultListModel<String> songListModel;

    /**
     * This will request LIST comman to the server and return it to the client
     */
    private void loadSongs() {

        List<String> songs = new ArrayList<>();
        try (Socket getSongSocket = new Socket(InetAddress.getByName("localhost"), serverPort);
                DataInputStream dis = new DataInputStream(getSongSocket.getInputStream());
                DataOutputStream dos = new DataOutputStream(getSongSocket.getOutputStream());) {
            // empty the list to load a new list with a new song uploaded (right now just
            // make it simple)
            emptyDefaultListSong();

            dos.writeUTF("LIST"); // Command to request get list songs

            int count = dis.readInt();

            for (int i = 0; i < count; i++) {
                songs.add(dis.readUTF());
            }

            for (String song : songs) {
                songListModel.addElement(song);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * I created this function to empty the default JList values because netbean
     * keep remove my code
     */
    private void emptyDefaultListSong() {
        songListModel = new DefaultListModel<>();
        listSongs.setModel(songListModel);
    }

    /**
     * Upload file
     */
    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();

            int result = fileChooser.showOpenDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                System.out.println("Selected File: " + selectedFile.getAbsolutePath() + " with size: "
                        + selectedFile.length());

                // // Create socket to send file after select file to upload
                try (Socket sendFile = new Socket(InetAddress.getByName("localhost"), serverPort);
                        DataInputStream dis = new DataInputStream(sendFile.getInputStream());
                        DataOutputStream dos = new DataOutputStream(sendFile.getOutputStream());
                        FileInputStream fis = new FileInputStream(selectedFile)) {
                    // Send command
                    dos.writeUTF("UPLOAD");

                    // Send file
                    dos.writeUTF(selectedFile.getName());

                    // Send file sizze
                    dos.writeLong(selectedFile.length());

                    // Send file data
                    byte[] buffer = new byte[4096];
                    int read;

                    while ((read = fis.read(buffer)) > 0) {
                        dos.write(buffer, 0, read);
                    }

                    String response = dis.readUTF();

                    if ("TRUE".equals(response)) {
                        JOptionPane.showMessageDialog(this, "Upload Successfully");
                        loadSongs();
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }

    }// GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnUpload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEndTimer;
    private javax.swing.JLabel lblSongName;
    private javax.swing.JLabel lblStartTimer;
    private javax.swing.JList<String> listSongs;
    private javax.swing.JProgressBar pbarAudioProgress;
    private javax.swing.JSlider slidAudioVolume;
    // End of variables declaration//GEN-END:variables

    private void setVolumeFromSlider(int sliderValue) {
        FloatControl gain = currentGainControl; // local snapshot
        if (gain != null) {
            float min = gain.getMinimum();
            float max = gain.getMaximum();
            float gainDb = (max - min) * (sliderValue / 100f) + min;
            try {
                gain.setValue(gainDb);
            } catch (IllegalArgumentException ignored) {
            }
        }
        // if currentGainControl is null, nothing to do yet; when discovered we apply
        // slider value
    }
}
